// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'ark/balance.dart';
import 'ark/client.dart';
import 'ark/esplora.dart';
import 'ark/server_info.dart';
import 'ark/transactions.dart';
import 'ark/utils.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class LibArk extends BaseEntrypoint<LibArkApi, LibArkApiImpl, LibArkWire> {
  @internal
  static final instance = LibArk._();

  LibArk._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    LibArkApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required LibArkApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<LibArkApiImpl, LibArkWire> get apiImplConstructor =>
      LibArkApiImpl.new;

  @override
  WireConstructor<LibArkWire> get wireConstructor =>
      LibArkWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1349188744;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ark_wallet',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class LibArkApi extends BaseApi {
  ArcClientEsploraClientWalletSqliteSwapStorage
  crateArkClientArkWalletAutoAccessorGetInner({required ArkWallet that});

  ArcVtxoWatcherHandle? crateArkClientArkWalletAutoAccessorGetWatcher({
    required ArkWallet that,
  });

  void crateArkClientArkWalletAutoAccessorSetInner({
    required ArkWallet that,
    required ArcClientEsploraClientWalletSqliteSwapStorage inner,
  });

  void crateArkClientArkWalletAutoAccessorSetWatcher({
    required ArkWallet that,
    ArcVtxoWatcherHandle? watcher,
  });

  Future<Balance> crateArkClientArkWalletBalance({required ArkWallet that});

  Future<String> crateArkClientArkWalletBoardingAddress({
    required ArkWallet that,
  });

  Future<String> crateArkClientArkWalletCollaborativeRedeem({
    required ArkWallet that,
    required String address,
    required PlatformInt64 sats,
  });

  Future<ArkWallet> crateArkClientArkWalletInit({
    required List<int> secretKey,
    required String network,
    required String esplora,
    required String server,
    required String boltz,
    required String dataDir,
    String? delegatorUrl,
  });

  Future<String> crateArkClientArkWalletOffchainAddress({
    required ArkWallet that,
  });

  Future<String> crateArkClientArkWalletSendOffChain({
    required ArkWallet that,
    required String address,
    required PlatformInt64 sats,
  });

  Future<String> crateArkClientArkWalletSendOnChain({
    required ArkWallet that,
    required String address,
    required PlatformInt64 sats,
  });

  Future<ServerInfo> crateArkClientArkWalletServerInfo({
    required ArkWallet that,
  });

  Future<String?> crateArkClientArkWalletSettle({required ArkWallet that});

  Future<List<Transaction>> crateArkClientArkWalletTransactionHistory({
    required ArkWallet that,
  });

  Future<void> crateArkEsploraEsploraClientCheckConnection({
    required EsploraClient that,
  });

  Future<EsploraClient> crateArkEsploraEsploraClientNew({required String url});

  bool crateArkUtilsUtilsIsArk({required String address});

  bool crateArkUtilsUtilsIsBtc({required String address});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcClientEsploraClientWalletSqliteSwapStorage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcClientEsploraClientWalletSqliteSwapStorage;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcClientEsploraClientWalletSqliteSwapStoragePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcVtxoWatcherHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcVtxoWatcherHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcVtxoWatcherHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArkWallet;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArkWallet;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ArkWalletPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_EsploraClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_EsploraClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EsploraClientPtr;
}

class LibArkApiImpl extends LibArkApiImplPlatform implements LibArkApi {
  LibArkApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ArcClientEsploraClientWalletSqliteSwapStorage
  crateArkClientArkWalletAutoAccessorGetInner({required ArkWallet that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage,
          decodeErrorData: null,
        ),
        constMeta: kCrateArkClientArkWalletAutoAccessorGetInnerConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletAutoAccessorGetInnerConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_auto_accessor_get_inner",
        argNames: ["that"],
      );

  @override
  ArcVtxoWatcherHandle? crateArkClientArkWalletAutoAccessorGetWatcher({
    required ArkWallet that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateArkClientArkWalletAutoAccessorGetWatcherConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletAutoAccessorGetWatcherConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_auto_accessor_get_watcher",
        argNames: ["that"],
      );

  @override
  void crateArkClientArkWalletAutoAccessorSetInner({
    required ArkWallet that,
    required ArcClientEsploraClientWalletSqliteSwapStorage inner,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage(
            inner,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateArkClientArkWalletAutoAccessorSetInnerConstMeta,
        argValues: [that, inner],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletAutoAccessorSetInnerConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_auto_accessor_set_inner",
        argNames: ["that", "inner"],
      );

  @override
  void crateArkClientArkWalletAutoAccessorSetWatcher({
    required ArkWallet that,
    ArcVtxoWatcherHandle? watcher,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
            watcher,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateArkClientArkWalletAutoAccessorSetWatcherConstMeta,
        argValues: [that, watcher],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletAutoAccessorSetWatcherConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_auto_accessor_set_watcher",
        argNames: ["that", "watcher"],
      );

  @override
  Future<Balance> crateArkClientArkWalletBalance({required ArkWallet that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_balance,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletBalanceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletBalanceConstMeta =>
      const TaskConstMeta(debugName: "ArkWallet_balance", argNames: ["that"]);

  @override
  Future<String> crateArkClientArkWalletBoardingAddress({
    required ArkWallet that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletBoardingAddressConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletBoardingAddressConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_boarding_address",
        argNames: ["that"],
      );

  @override
  Future<String> crateArkClientArkWalletCollaborativeRedeem({
    required ArkWallet that,
    required String address,
    required PlatformInt64 sats,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          sse_encode_String(address, serializer);
          sse_encode_i_64(sats, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletCollaborativeRedeemConstMeta,
        argValues: [that, address, sats],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletCollaborativeRedeemConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_collaborative_redeem",
        argNames: ["that", "address", "sats"],
      );

  @override
  Future<ArkWallet> crateArkClientArkWalletInit({
    required List<int> secretKey,
    required String network,
    required String esplora,
    required String server,
    required String boltz,
    required String dataDir,
    String? delegatorUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secretKey, serializer);
          sse_encode_String(network, serializer);
          sse_encode_String(esplora, serializer);
          sse_encode_String(server, serializer);
          sse_encode_String(boltz, serializer);
          sse_encode_String(dataDir, serializer);
          sse_encode_opt_String(delegatorUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletInitConstMeta,
        argValues: [
          secretKey,
          network,
          esplora,
          server,
          boltz,
          dataDir,
          delegatorUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletInitConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_init",
        argNames: [
          "secretKey",
          "network",
          "esplora",
          "server",
          "boltz",
          "dataDir",
          "delegatorUrl",
        ],
      );

  @override
  Future<String> crateArkClientArkWalletOffchainAddress({
    required ArkWallet that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletOffchainAddressConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletOffchainAddressConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_offchain_address",
        argNames: ["that"],
      );

  @override
  Future<String> crateArkClientArkWalletSendOffChain({
    required ArkWallet that,
    required String address,
    required PlatformInt64 sats,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          sse_encode_String(address, serializer);
          sse_encode_i_64(sats, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletSendOffChainConstMeta,
        argValues: [that, address, sats],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletSendOffChainConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_send_off_chain",
        argNames: ["that", "address", "sats"],
      );

  @override
  Future<String> crateArkClientArkWalletSendOnChain({
    required ArkWallet that,
    required String address,
    required PlatformInt64 sats,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          sse_encode_String(address, serializer);
          sse_encode_i_64(sats, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletSendOnChainConstMeta,
        argValues: [that, address, sats],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletSendOnChainConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_send_on_chain",
        argNames: ["that", "address", "sats"],
      );

  @override
  Future<ServerInfo> crateArkClientArkWalletServerInfo({
    required ArkWallet that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_server_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletServerInfoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletServerInfoConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_server_info",
        argNames: ["that"],
      );

  @override
  Future<String?> crateArkClientArkWalletSettle({required ArkWallet that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletSettleConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletSettleConstMeta =>
      const TaskConstMeta(debugName: "ArkWallet_settle", argNames: ["that"]);

  @override
  Future<List<Transaction>> crateArkClientArkWalletTransactionHistory({
    required ArkWallet that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_transaction,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkClientArkWalletTransactionHistoryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkClientArkWalletTransactionHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "ArkWallet_transaction_history",
        argNames: ["that"],
      );

  @override
  Future<void> crateArkEsploraEsploraClientCheckConnection({
    required EsploraClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkEsploraEsploraClientCheckConnectionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkEsploraEsploraClientCheckConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "EsploraClient_check_connection",
        argNames: ["that"],
      );

  @override
  Future<EsploraClient> crateArkEsploraEsploraClientNew({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateArkEsploraEsploraClientNewConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkEsploraEsploraClientNewConstMeta =>
      const TaskConstMeta(debugName: "EsploraClient_new", argNames: ["url"]);

  @override
  bool crateArkUtilsUtilsIsArk({required String address}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateArkUtilsUtilsIsArkConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkUtilsUtilsIsArkConstMeta =>
      const TaskConstMeta(debugName: "utils_is_ark", argNames: ["address"]);

  @override
  bool crateArkUtilsUtilsIsBtc({required String address}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateArkUtilsUtilsIsBtcConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateArkUtilsUtilsIsBtcConstMeta =>
      const TaskConstMeta(debugName: "utils_is_btc", argNames: ["address"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcClientEsploraClientWalletSqliteSwapStorage =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcClientEsploraClientWalletSqliteSwapStorage =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcVtxoWatcherHandle =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcVtxoWatcherHandle =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArkWallet =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArkWallet =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_EsploraClient =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_EsploraClient =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ArcClientEsploraClientWalletSqliteSwapStorage
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcClientEsploraClientWalletSqliteSwapStorageImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ArcVtxoWatcherHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcVtxoWatcherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArkWallet
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArkWalletImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EsploraClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EsploraClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArkWallet
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArkWalletImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArkWallet
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArkWalletImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EsploraClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EsploraClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcClientEsploraClientWalletSqliteSwapStorage
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcClientEsploraClientWalletSqliteSwapStorageImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ArcVtxoWatcherHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcVtxoWatcherHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArkWallet
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArkWalletImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EsploraClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EsploraClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Balance dco_decode_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Balance(
      preConfirmed: dco_decode_i_64(arr[0]),
      confirmed: dco_decode_i_64(arr[1]),
      recoverable: dco_decode_i_64(arr[2]),
      pendingRecovery: dco_decode_i_64(arr[3]),
      total: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ArcVtxoWatcherHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
      raw,
    );
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Transaction> dco_decode_list_transaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_transaction).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ArcVtxoWatcherHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
          raw,
        );
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  ServerInfo dco_decode_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 19)
      throw Exception('unexpected arr length: expect 19 but see ${arr.length}');
    return ServerInfo(
      version: dco_decode_String(arr[0]),
      signerPubkey: dco_decode_String(arr[1]),
      forfeitPubkey: dco_decode_String(arr[2]),
      forfeitAddress: dco_decode_String(arr[3]),
      checkpointTapscript: dco_decode_String(arr[4]),
      network: dco_decode_String(arr[5]),
      sessionDuration: dco_decode_i_64(arr[6]),
      unilateralExitDelay: dco_decode_u_32(arr[7]),
      unilateralExitDelaySeconds: dco_decode_opt_box_autoadd_i_64(arr[8]),
      unilateralExitDelayBlocks: dco_decode_opt_box_autoadd_u_32(arr[9]),
      boardingExitDelay: dco_decode_u_32(arr[10]),
      boardingExitDelaySeconds: dco_decode_opt_box_autoadd_i_64(arr[11]),
      boardingExitDelayBlocks: dco_decode_opt_box_autoadd_u_32(arr[12]),
      utxoMinAmount: dco_decode_opt_box_autoadd_i_64(arr[13]),
      utxoMaxAmount: dco_decode_opt_box_autoadd_i_64(arr[14]),
      vtxoMinAmount: dco_decode_opt_box_autoadd_i_64(arr[15]),
      vtxoMaxAmount: dco_decode_opt_box_autoadd_i_64(arr[16]),
      dust: dco_decode_i_64(arr[17]),
      digest: dco_decode_String(arr[18]),
    );
  }

  @protected
  Transaction dco_decode_transaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Transaction_Boarding(
          txid: dco_decode_String(raw[1]),
          sats: dco_decode_i_64(raw[2]),
          confirmedAt: dco_decode_opt_box_autoadd_i_64(raw[3]),
        );
      case 1:
        return Transaction_Commitment(
          txid: dco_decode_String(raw[1]),
          sats: dco_decode_i_64(raw[2]),
          createdAt: dco_decode_i_64(raw[3]),
        );
      case 2:
        return Transaction_Redeem(
          txid: dco_decode_String(raw[1]),
          sats: dco_decode_i_64(raw[2]),
          isSettled: dco_decode_bool(raw[3]),
          createdAt: dco_decode_i_64(raw[4]),
        );
      case 3:
        return Transaction_Offboard(
          commitmentTxid: dco_decode_String(raw[1]),
          sats: dco_decode_i_64(raw[2]),
          confirmedAt: dco_decode_opt_box_autoadd_i_64(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Utils dco_decode_utils(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.isNotEmpty)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return Utils();
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ArcClientEsploraClientWalletSqliteSwapStorage
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcClientEsploraClientWalletSqliteSwapStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcVtxoWatcherHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcVtxoWatcherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArkWallet
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArkWalletImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EsploraClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EsploraClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArkWallet
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArkWalletImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArkWallet
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArkWalletImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EsploraClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EsploraClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcClientEsploraClientWalletSqliteSwapStorage
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcClientEsploraClientWalletSqliteSwapStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcVtxoWatcherHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcVtxoWatcherHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArkWallet
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArkWalletImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  EsploraClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EsploraClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Balance sse_decode_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_preConfirmed = sse_decode_i_64(deserializer);
    var var_confirmed = sse_decode_i_64(deserializer);
    var var_recoverable = sse_decode_i_64(deserializer);
    var var_pendingRecovery = sse_decode_i_64(deserializer);
    var var_total = sse_decode_i_64(deserializer);
    return Balance(
      preConfirmed: var_preConfirmed,
      confirmed: var_confirmed,
      recoverable: var_recoverable,
      pendingRecovery: var_pendingRecovery,
      total: var_total,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ArcVtxoWatcherHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
      deserializer,
    ));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Transaction> sse_decode_list_transaction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Transaction>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transaction(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ArcVtxoWatcherHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_String(deserializer);
    var var_signerPubkey = sse_decode_String(deserializer);
    var var_forfeitPubkey = sse_decode_String(deserializer);
    var var_forfeitAddress = sse_decode_String(deserializer);
    var var_checkpointTapscript = sse_decode_String(deserializer);
    var var_network = sse_decode_String(deserializer);
    var var_sessionDuration = sse_decode_i_64(deserializer);
    var var_unilateralExitDelay = sse_decode_u_32(deserializer);
    var var_unilateralExitDelaySeconds = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_unilateralExitDelayBlocks = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_boardingExitDelay = sse_decode_u_32(deserializer);
    var var_boardingExitDelaySeconds = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_boardingExitDelayBlocks = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_utxoMinAmount = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_utxoMaxAmount = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_vtxoMinAmount = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_vtxoMaxAmount = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_dust = sse_decode_i_64(deserializer);
    var var_digest = sse_decode_String(deserializer);
    return ServerInfo(
      version: var_version,
      signerPubkey: var_signerPubkey,
      forfeitPubkey: var_forfeitPubkey,
      forfeitAddress: var_forfeitAddress,
      checkpointTapscript: var_checkpointTapscript,
      network: var_network,
      sessionDuration: var_sessionDuration,
      unilateralExitDelay: var_unilateralExitDelay,
      unilateralExitDelaySeconds: var_unilateralExitDelaySeconds,
      unilateralExitDelayBlocks: var_unilateralExitDelayBlocks,
      boardingExitDelay: var_boardingExitDelay,
      boardingExitDelaySeconds: var_boardingExitDelaySeconds,
      boardingExitDelayBlocks: var_boardingExitDelayBlocks,
      utxoMinAmount: var_utxoMinAmount,
      utxoMaxAmount: var_utxoMaxAmount,
      vtxoMinAmount: var_vtxoMinAmount,
      vtxoMaxAmount: var_vtxoMaxAmount,
      dust: var_dust,
      digest: var_digest,
    );
  }

  @protected
  Transaction sse_decode_transaction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_txid = sse_decode_String(deserializer);
        var var_sats = sse_decode_i_64(deserializer);
        var var_confirmedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
        return Transaction_Boarding(
          txid: var_txid,
          sats: var_sats,
          confirmedAt: var_confirmedAt,
        );
      case 1:
        var var_txid = sse_decode_String(deserializer);
        var var_sats = sse_decode_i_64(deserializer);
        var var_createdAt = sse_decode_i_64(deserializer);
        return Transaction_Commitment(
          txid: var_txid,
          sats: var_sats,
          createdAt: var_createdAt,
        );
      case 2:
        var var_txid = sse_decode_String(deserializer);
        var var_sats = sse_decode_i_64(deserializer);
        var var_isSettled = sse_decode_bool(deserializer);
        var var_createdAt = sse_decode_i_64(deserializer);
        return Transaction_Redeem(
          txid: var_txid,
          sats: var_sats,
          isSettled: var_isSettled,
          createdAt: var_createdAt,
        );
      case 3:
        var var_commitmentTxid = sse_decode_String(deserializer);
        var var_sats = sse_decode_i_64(deserializer);
        var var_confirmedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
        return Transaction_Offboard(
          commitmentTxid: var_commitmentTxid,
          sats: var_sats,
          confirmedAt: var_confirmedAt,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Utils sse_decode_utils(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Utils();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage(
    ArcClientEsploraClientWalletSqliteSwapStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcClientEsploraClientWalletSqliteSwapStorageImpl)
          .frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    ArcVtxoWatcherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcVtxoWatcherHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArkWalletImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EsploraClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArkWalletImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArkWalletImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EsploraClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcClientEsploraClientWalletSqliteSwapStorage(
    ArcClientEsploraClientWalletSqliteSwapStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcClientEsploraClientWalletSqliteSwapStorageImpl)
          .frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    ArcVtxoWatcherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcVtxoWatcherHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArkWalletImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as EsploraClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_balance(Balance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.preConfirmed, serializer);
    sse_encode_i_64(self.confirmed, serializer);
    sse_encode_i_64(self.recoverable, serializer);
    sse_encode_i_64(self.pendingRecovery, serializer);
    sse_encode_i_64(self.total, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    ArcVtxoWatcherHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_transaction(
    List<Transaction> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transaction(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
    ArcVtxoWatcherHandle? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcVtxoWatcherHandle(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.signerPubkey, serializer);
    sse_encode_String(self.forfeitPubkey, serializer);
    sse_encode_String(self.forfeitAddress, serializer);
    sse_encode_String(self.checkpointTapscript, serializer);
    sse_encode_String(self.network, serializer);
    sse_encode_i_64(self.sessionDuration, serializer);
    sse_encode_u_32(self.unilateralExitDelay, serializer);
    sse_encode_opt_box_autoadd_i_64(
      self.unilateralExitDelaySeconds,
      serializer,
    );
    sse_encode_opt_box_autoadd_u_32(self.unilateralExitDelayBlocks, serializer);
    sse_encode_u_32(self.boardingExitDelay, serializer);
    sse_encode_opt_box_autoadd_i_64(self.boardingExitDelaySeconds, serializer);
    sse_encode_opt_box_autoadd_u_32(self.boardingExitDelayBlocks, serializer);
    sse_encode_opt_box_autoadd_i_64(self.utxoMinAmount, serializer);
    sse_encode_opt_box_autoadd_i_64(self.utxoMaxAmount, serializer);
    sse_encode_opt_box_autoadd_i_64(self.vtxoMinAmount, serializer);
    sse_encode_opt_box_autoadd_i_64(self.vtxoMaxAmount, serializer);
    sse_encode_i_64(self.dust, serializer);
    sse_encode_String(self.digest, serializer);
  }

  @protected
  void sse_encode_transaction(Transaction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Transaction_Boarding(
        txid: final txid,
        sats: final sats,
        confirmedAt: final confirmedAt,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(txid, serializer);
        sse_encode_i_64(sats, serializer);
        sse_encode_opt_box_autoadd_i_64(confirmedAt, serializer);
      case Transaction_Commitment(
        txid: final txid,
        sats: final sats,
        createdAt: final createdAt,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(txid, serializer);
        sse_encode_i_64(sats, serializer);
        sse_encode_i_64(createdAt, serializer);
      case Transaction_Redeem(
        txid: final txid,
        sats: final sats,
        isSettled: final isSettled,
        createdAt: final createdAt,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(txid, serializer);
        sse_encode_i_64(sats, serializer);
        sse_encode_bool(isSettled, serializer);
        sse_encode_i_64(createdAt, serializer);
      case Transaction_Offboard(
        commitmentTxid: final commitmentTxid,
        sats: final sats,
        confirmedAt: final confirmedAt,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(commitmentTxid, serializer);
        sse_encode_i_64(sats, serializer);
        sse_encode_opt_box_autoadd_i_64(confirmedAt, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_utils(Utils self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ArcClientEsploraClientWalletSqliteSwapStorageImpl extends RustOpaque
    implements ArcClientEsploraClientWalletSqliteSwapStorage {
  // Not to be used by end users
  ArcClientEsploraClientWalletSqliteSwapStorageImpl.frbInternalDcoDecode(
    List<dynamic> wire,
  ) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcClientEsploraClientWalletSqliteSwapStorageImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        LibArk
            .instance
            .api
            .rust_arc_increment_strong_count_ArcClientEsploraClientWalletSqliteSwapStorage,
    rustArcDecrementStrongCount:
        LibArk
            .instance
            .api
            .rust_arc_decrement_strong_count_ArcClientEsploraClientWalletSqliteSwapStorage,
    rustArcDecrementStrongCountPtr:
        LibArk
            .instance
            .api
            .rust_arc_decrement_strong_count_ArcClientEsploraClientWalletSqliteSwapStoragePtr,
  );
}

@sealed
class ArcVtxoWatcherHandleImpl extends RustOpaque
    implements ArcVtxoWatcherHandle {
  // Not to be used by end users
  ArcVtxoWatcherHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcVtxoWatcherHandleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        LibArk
            .instance
            .api
            .rust_arc_increment_strong_count_ArcVtxoWatcherHandle,
    rustArcDecrementStrongCount:
        LibArk
            .instance
            .api
            .rust_arc_decrement_strong_count_ArcVtxoWatcherHandle,
    rustArcDecrementStrongCountPtr:
        LibArk
            .instance
            .api
            .rust_arc_decrement_strong_count_ArcVtxoWatcherHandlePtr,
  );
}

@sealed
class ArkWalletImpl extends RustOpaque implements ArkWallet {
  // Not to be used by end users
  ArkWalletImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArkWalletImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        LibArk.instance.api.rust_arc_increment_strong_count_ArkWallet,
    rustArcDecrementStrongCount:
        LibArk.instance.api.rust_arc_decrement_strong_count_ArkWallet,
    rustArcDecrementStrongCountPtr:
        LibArk.instance.api.rust_arc_decrement_strong_count_ArkWalletPtr,
  );

  ArcClientEsploraClientWalletSqliteSwapStorage get inner => LibArk.instance.api
      .crateArkClientArkWalletAutoAccessorGetInner(that: this);

  ArcVtxoWatcherHandle? get watcher => LibArk.instance.api
      .crateArkClientArkWalletAutoAccessorGetWatcher(that: this);

  set inner(ArcClientEsploraClientWalletSqliteSwapStorage inner) => LibArk
      .instance
      .api
      .crateArkClientArkWalletAutoAccessorSetInner(that: this, inner: inner);

  set watcher(ArcVtxoWatcherHandle? watcher) =>
      LibArk.instance.api.crateArkClientArkWalletAutoAccessorSetWatcher(
        that: this,
        watcher: watcher,
      );

  Future<Balance> balance() =>
      LibArk.instance.api.crateArkClientArkWalletBalance(that: this);

  /// Bitcoin boarding address, for moving on-chain funds into Ark.
  Future<String> boardingAddress() =>
      LibArk.instance.api.crateArkClientArkWalletBoardingAddress(that: this);

  /// Offboard to an on-chain address with the operator's cooperation.
  ///
  /// Recoverable (expired) VTXOs are now selected by the SDK automatically, so the previous
  /// `select_recoverable_vtxos` flag no longer exists.
  Future<String> collaborativeRedeem({
    required String address,
    required PlatformInt64 sats,
  }) => LibArk.instance.api.crateArkClientArkWalletCollaborativeRedeem(
    that: this,
    address: address,
    sats: sats,
  );

  /// Ark (off-chain) address. Now async: the SDK derives it through the key provider.
  Future<String> offchainAddress() =>
      LibArk.instance.api.crateArkClientArkWalletOffchainAddress(that: this);

  Future<String> sendOffChain({
    required String address,
    required PlatformInt64 sats,
  }) => LibArk.instance.api.crateArkClientArkWalletSendOffChain(
    that: this,
    address: address,
    sats: sats,
  );

  Future<String> sendOnChain({
    required String address,
    required PlatformInt64 sats,
  }) => LibArk.instance.api.crateArkClientArkWalletSendOnChain(
    that: this,
    address: address,
    sats: sats,
  );

  Future<ServerInfo> serverInfo() =>
      LibArk.instance.api.crateArkClientArkWalletServerInfo(that: this);

  /// Settle (renew) VTXOs into a fresh batch.
  ///
  /// Returns the commitment txid, or `None` when there was nothing to settle. The SDK now picks
  /// up recoverable VTXOs on its own, so the previous `select_recoverable_vtxos` flag is gone.
  Future<String?> settle() =>
      LibArk.instance.api.crateArkClientArkWalletSettle(that: this);

  Future<List<Transaction>> transactionHistory() =>
      LibArk.instance.api.crateArkClientArkWalletTransactionHistory(that: this);
}

@sealed
class EsploraClientImpl extends RustOpaque implements EsploraClient {
  // Not to be used by end users
  EsploraClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EsploraClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        LibArk.instance.api.rust_arc_increment_strong_count_EsploraClient,
    rustArcDecrementStrongCount:
        LibArk.instance.api.rust_arc_decrement_strong_count_EsploraClient,
    rustArcDecrementStrongCountPtr:
        LibArk.instance.api.rust_arc_decrement_strong_count_EsploraClientPtr,
  );

  Future<void> checkConnection() => LibArk.instance.api
      .crateArkEsploraEsploraClientCheckConnection(that: this);
}
