// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Balance {
  /// Received but not yet confirmed in a batch. Was called `pending` before.
  final PlatformInt64 preConfirmed;
  final PlatformInt64 confirmed;

  /// VTXOs whose batch has expired. Still spendable, but only via a settle/renewal - they can no
  /// longer be exited unilaterally until renewed.
  final PlatformInt64 recoverable;

  /// Funds under a deprecated server signer past its cutoff. Not spendable offchain; becomes
  /// `recoverable` once the VTXO expires.
  final PlatformInt64 pendingRecovery;
  final PlatformInt64 total;

  const Balance({
    required this.preConfirmed,
    required this.confirmed,
    required this.recoverable,
    required this.pendingRecovery,
    required this.total,
  });

  @override
  int get hashCode =>
      preConfirmed.hashCode ^
      confirmed.hashCode ^
      recoverable.hashCode ^
      pendingRecovery.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Balance &&
          runtimeType == other.runtimeType &&
          preConfirmed == other.preConfirmed &&
          confirmed == other.confirmed &&
          recoverable == other.recoverable &&
          pendingRecovery == other.pendingRecovery &&
          total == other.total;
}
