// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'balance.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'server_info.dart';
import 'subscribe.dart';
import 'transactions.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ArkWallet>>
abstract class ArkWallet implements RustOpaqueInterface {
  ArkDelegate? get delegate;

  ArcClientEsploraClientWalletSqliteSwapStorage get inner;

  ArcVtxoWatcherHandle? get watcher;

  set delegate(ArkDelegate? delegate);

  set inner(ArcClientEsploraClientWalletSqliteSwapStorage inner);

  set watcher(ArcVtxoWatcherHandle? watcher);

  Future<Balance> balance();

  /// Bitcoin boarding address, for moving on-chain funds into Ark.
  Future<String> boardingAddress();

  /// Offboard to an on-chain address with the operator's cooperation.
  ///
  /// Recoverable (expired) VTXOs are now selected by the SDK automatically, so the previous
  /// `select_recoverable_vtxos` flag no longer exists.
  Future<String> collaborativeRedeem({
    required String address,
    required PlatformInt64 sats,
  });

  /// The delegate authorised to renew this wallet's VTXOs, if any.
  Future<ArkDelegate?> delegateInfo();

  /// Initialise an Ark wallet.
  ///
  /// `secret_key` is a BIP32 seed of 16 to 64 bytes - pass the wallet's BIP39 seed directly so
  /// that Ark derives from the same master key as the rest of the wallet, and the mnemonic alone
  /// is enough to recover Ark funds. The on-chain wallet and the Ark identity keys are both
  /// derived from it, so the same seed always yields the same addresses on a given network.
  ///
  /// `network` accepts the values understood by rust-bitcoin: `bitcoin` (mainnet), `signet`,
  /// `testnet` and `regtest`. Note that `mainnet` is *not* a valid value.
  ///
  /// `data_dir` is a writable directory used to persist swap state across restarts. It is
  /// created if it does not exist.
  ///
  /// `delegator_url` opts into delegated renewal. A delegate can only renew VTXOs - it cannot
  /// move funds - but it changes the addresses this wallet produces, because a delegated VTXO
  /// carries a third Taproot leaf. Enabling or disabling it later therefore yields different
  /// addresses, so decide before funds arrive.
  static Future<ArkWallet> init({
    required List<int> secretKey,
    required String network,
    required String esplora,
    required String server,
    required String boltz,
    required String dataDir,
    String? delegatorUrl,
  }) => LibArk.instance.api.crateArkClientArkWalletInit(
    secretKey: secretKey,
    network: network,
    esplora: esplora,
    server: server,
    boltz: boltz,
    dataDir: dataDir,
    delegatorUrl: delegatorUrl,
  );

  /// Ark (off-chain) address. Now async: the SDK derives it through the key provider.
  Future<String> offchainAddress();

  Future<String> sendOffChain({
    required String address,
    required PlatformInt64 sats,
  });

  Future<String> sendOnChain({
    required String address,
    required PlatformInt64 sats,
  });

  Future<ServerInfo> serverInfo();

  /// Settle (renew) VTXOs into a fresh batch.
  ///
  /// Returns the commitment txid, or `None` when there was nothing to settle. The SDK now picks
  /// up recoverable VTXOs on its own, so the previous `select_recoverable_vtxos` flag is gone.
  Future<String?> settle();

  Future<List<Transaction>> transactionHistory();

  /// Stream VTXOs arriving on this wallet's off-chain address.
  ///
  /// The returned stream stays open until the server closes it or the Dart side stops
  /// listening. Errors end the stream rather than being retried here, so the caller decides
  /// whether to resubscribe.
  Stream<ArkIncomingPayment> watchIncomingPayments();
}

/// The delegate this wallet renews through, as reported by the service itself.
///
/// Read-only: the delegate is part of every address the wallet derives, so it cannot be changed
/// once funds exist. Exposed so the wallet can show who is authorised to renew its VTXOs.
class ArkDelegate {
  final String url;

  /// Hex-encoded public key. This key appears in the third Taproot leaf of every VTXO.
  final String pubkey;

  /// What the service charges per renewal, in sats, verbatim as it reported it.
  final String fee;

  /// Where the service collects its fee on-chain.
  final String address;

  const ArkDelegate({
    required this.url,
    required this.pubkey,
    required this.fee,
    required this.address,
  });

  @override
  int get hashCode =>
      url.hashCode ^ pubkey.hashCode ^ fee.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArkDelegate &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          pubkey == other.pubkey &&
          fee == other.fee &&
          address == other.address;
}
