// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_blocks`, `decode_seconds`

class ServerInfo {
  final String version;
  final String signerPubkey;
  final String forfeitPubkey;
  final String forfeitAddress;
  final String checkpointTapscript;
  final String network;
  final PlatformInt64 sessionDuration;

  /// Raw BIP68 sequence value. Prefer the decoded `*_seconds` / `*_blocks` fields below:
  /// the raw number is an encoding, not a duration.
  final int unilateralExitDelay;

  /// Decoded delay in seconds, when the timelock is time-based.
  final PlatformInt64? unilateralExitDelaySeconds;

  /// Decoded delay in blocks, when the timelock is height-based.
  final int? unilateralExitDelayBlocks;
  final int boardingExitDelay;
  final PlatformInt64? boardingExitDelaySeconds;
  final int? boardingExitDelayBlocks;
  final PlatformInt64? utxoMinAmount;
  final PlatformInt64? utxoMaxAmount;
  final PlatformInt64? vtxoMinAmount;
  final PlatformInt64? vtxoMaxAmount;
  final PlatformInt64 dust;
  final String digest;

  const ServerInfo({
    required this.version,
    required this.signerPubkey,
    required this.forfeitPubkey,
    required this.forfeitAddress,
    required this.checkpointTapscript,
    required this.network,
    required this.sessionDuration,
    required this.unilateralExitDelay,
    this.unilateralExitDelaySeconds,
    this.unilateralExitDelayBlocks,
    required this.boardingExitDelay,
    this.boardingExitDelaySeconds,
    this.boardingExitDelayBlocks,
    this.utxoMinAmount,
    this.utxoMaxAmount,
    this.vtxoMinAmount,
    this.vtxoMaxAmount,
    required this.dust,
    required this.digest,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      signerPubkey.hashCode ^
      forfeitPubkey.hashCode ^
      forfeitAddress.hashCode ^
      checkpointTapscript.hashCode ^
      network.hashCode ^
      sessionDuration.hashCode ^
      unilateralExitDelay.hashCode ^
      unilateralExitDelaySeconds.hashCode ^
      unilateralExitDelayBlocks.hashCode ^
      boardingExitDelay.hashCode ^
      boardingExitDelaySeconds.hashCode ^
      boardingExitDelayBlocks.hashCode ^
      utxoMinAmount.hashCode ^
      utxoMaxAmount.hashCode ^
      vtxoMinAmount.hashCode ^
      vtxoMaxAmount.hashCode ^
      dust.hashCode ^
      digest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          signerPubkey == other.signerPubkey &&
          forfeitPubkey == other.forfeitPubkey &&
          forfeitAddress == other.forfeitAddress &&
          checkpointTapscript == other.checkpointTapscript &&
          network == other.network &&
          sessionDuration == other.sessionDuration &&
          unilateralExitDelay == other.unilateralExitDelay &&
          unilateralExitDelaySeconds == other.unilateralExitDelaySeconds &&
          unilateralExitDelayBlocks == other.unilateralExitDelayBlocks &&
          boardingExitDelay == other.boardingExitDelay &&
          boardingExitDelaySeconds == other.boardingExitDelaySeconds &&
          boardingExitDelayBlocks == other.boardingExitDelayBlocks &&
          utxoMinAmount == other.utxoMinAmount &&
          utxoMaxAmount == other.utxoMaxAmount &&
          vtxoMinAmount == other.vtxoMinAmount &&
          vtxoMaxAmount == other.vtxoMaxAmount &&
          dust == other.dust &&
          digest == other.digest;
}
