// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A VTXO that has just appeared on one of this wallet's addresses.
///
/// Ark payments settle off-chain, so nothing on the Bitcoin chain announces them. Without a
/// subscription the only way to notice one is to poll, which is both slow and wasteful.
class ArkIncomingPayment {
  final String txid;
  final int vout;
  final PlatformInt64 amount;

  /// A pre-confirmed VTXO spends from another VTXO rather than being a batch-tree leaf. It is
  /// immediately spendable off-chain, so for display purposes it counts as received.
  final bool isPreconfirmed;

  const ArkIncomingPayment({
    required this.txid,
    required this.vout,
    required this.amount,
    required this.isPreconfirmed,
  });

  @override
  int get hashCode =>
      txid.hashCode ^ vout.hashCode ^ amount.hashCode ^ isPreconfirmed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArkIncomingPayment &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          amount == other.amount &&
          isPreconfirmed == other.isPreconfirmed;
}
