// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'transactions.freezed.dart';

@freezed
sealed class Transaction with _$Transaction {
  const Transaction._();

  const factory Transaction.boarding({
    required String txid,
    required PlatformInt64 sats,
    PlatformInt64? confirmedAt,
  }) = Transaction_Boarding;
  const factory Transaction.commitment({
    required String txid,
    required PlatformInt64 sats,
    required PlatformInt64 createdAt,
  }) = Transaction_Commitment;
  const factory Transaction.redeem({
    required String txid,
    required PlatformInt64 sats,
    required bool isSettled,
    required PlatformInt64 createdAt,
  }) = Transaction_Redeem;

  /// VTXOs offboarded to an on-chain output. Always outgoing.
  const factory Transaction.offboard({
    required String commitmentTxid,
    required PlatformInt64 sats,
    PlatformInt64? confirmedAt,
  }) = Transaction_Offboard;
}
